### ISSUE TITLE
Exceeding the maximum size limit in Analysis table for some records

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#205]
When we run the analysis for yiwang, we get an error:
```
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Item size has exceeded the maximum allowed size (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: Q688NK1IGVHT27G4MNKSO2P5ENVV4KQNSO5AEMVJF66Q9ASUAAJG)
```

This is because we [can't modify the item size limit](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-items) in DynamoDB, and records like yiwang are exceeding that limit.

There are a [few options](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-use-s3-too.html) for storing larger items:

1. Compress them.
2. Store a pointer to an S3 object that stores the larger item.

Investigate whether roles are the culprit...
```
AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
DynamoDBAutoscaleRole
```

**Comment by jl987-Jie** [comment]
The suggested design to resolve 

```
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Item size has exceeded the maximum allowed size (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: Q688NK1IGVHT27G4MNKSO2P5ENVV4KQNSO5AEMVJF66Q9ASUAAJG)
```

is to insert smaller ReCiter features into the `Analysis` table.

### Current design 
The current design stores ReCiter's analysis output in the `Analysis` table that contains the general metrics of the clustering performance such as the overall accuracy, precision, recall, uid, etc. It also contains the list of PubMed articles and its corresponding features (i.e, the article's title, journal, its list of positive evidences which contains reasons behind matching the author and the article, etc). For some authors such as `yiwang`, the number of articles that needs to be clustered is greater than 10,000. When ReCiter runs the clustering algorithm and store the clustering result into the DynamoDB table, DynamoDB throws an exception stating `Item size has exceeded the maximum allowed size`.

A sample analysis result looks like the following:

```
{
  "reCiterFeature": {
    "M": {
      "countSuggestedArticles": {
        "N": "61"
      },
      "dateAdded": {
        "S": "2018-05-17T19:17:20.002Z"
      },
      "dateUpdated": {
        "S": "2018-05-17T19:17:20.002Z"
      },
      "inGoldStandardButNotRetrieved": {
        "L": []
      },
      "mode": {
        "S": "test"
      },
      "overallAccuracy": {
        "N": "0.5819672131147541"
      },
      "personIdentifier": {
        "S": "paa2013"
      },
      "precision": {
        "N": "0.16393442622950818"
      },
      "recall": {
        "N": "1"
      },
      "reCiterArticleFeatures": {
        "L": [
          {
            "M": {
              "articleTitle": {
                "S": "Perception of aspen and sun/shade sugar maple leaf soluble extracts by larvae of Malacosoma disstria."
              },
              "issue": {
                "S": "10"
              },
              "journalTitleISOabbreviation": {
                "S": "J. Chem. Ecol."
              },
              "journalTitleVerbose": {
                "S": "Journal of chemical ecology"
              },
              "pages": {
                "S": "1963-78"
              },
              "pmid": {
                "N": "11710605"
              },
              "positiveEvidence": {
                "M": {
                  "authorNameEvidence": {
                    "M": {
                      "articleAuthorName": {
                        "M": {
                          "firstInitial": {
                            "S": "P"
                          },
                          "firstName": {
                            "S": "P"
                          },
                          "lastName": {
                            "S": "Albert"
                          },
                          "middleInitial": {
                            "S": "J"
                          },
                          "middleName": {
                            "S": "J"
                          }
                        }
                      },
                      "institutionalAuthorName": {
                        "M": {
                          "firstInitial": {
                            "S": "P"
                          },
                          "firstName": {
                            "S": "Paul"
                          },
                          "lastName": {
                            "S": "Albert"
                          },
                          "middleInitial": {
                            "S": "J"
                          },
                          "middleName": {
                            "S": "J"
                          }
                        }
                      }
                    }
                  },
                  "clusteringEvidence": {
                    "M": {
                      "bibliographicCoupling": {
                        "L": []
                      },
                      "citedBy": {
                        "L": []
                      },
                      "cites": {
                        "L": []
                      }
                    }
                  },
                  "educationYearEvidence": {
                    "M": {
                      "discrepancyDegreeYearBachelor": {
                        "N": "4"
                      },
                      "discrepancyDegreeYearTerminal": {
                        "N": "0"
                      }
                    }
                  },
                  "relationshipEvidences": {
                    "L": []
                  }
                }
              },
              "reCiterArticleAuthorFeatures": {
                "L": [
                  {
                    "M": {
                      "firstName": {
                        "S": "M"
                      },
                      "initials": {
                        "S": "M"
                      },
                      "lastName": {
                        "S": "Panzuto"
                      },
                      "rank": {
                        "N": "1"
                      },
                      "targetAuthor": {
                        "N": "0"
                      }
                    }
                  },
                  {
                    "M": {
                      "firstName": {
                        "S": "F"
                      },
                      "initials": {
                        "S": "F"
                      },
                      "lastName": {
                        "S": "Lorenzetti"
                      },
                      "rank": {
                        "N": "2"
                      },
                      "targetAuthor": {
                        "N": "0"
                      }
                    }
                  },
                  {
                    "M": {
                      "firstName": {
                        "S": "Y"
                      },
                      "initials": {
                        "S": "Y"
                      },
                      "lastName": {
                        "S": "Mauffette"
                      },
                      "rank": {
                        "N": "3"
                      },
                      "targetAuthor": {
                        "N": "0"
                      }
                    }
                  },
                  {
                    "M": {
                      "firstName": {
                        "S": "P"
                      },
                      "initials": {
                        "S": "P"
                      },
                      "lastName": {
                        "S": "Albert"
                      },
                      "rank": {
                        "N": "4"
                      },
                      "targetAuthor": {
                        "N": "1"
                      }
                    }
                  }
                ]
              },
              "score": {
                "N": "0"
              },
              "userAssertion": {
                "N": "0"
              },
              "volume": {
                "S": "27"
              }
            }
          },
          "uid": {
    "S": "paa2013"
  }
}
```

Proposed solutions:

#### Store a smaller item into DyanamoDB table that doesn't violate its limit.

In order to decrease the size of the output, ReCiter will store the general result and each of the article features into its own respective rows of the DynamoDB table. This means that the Analysis table will contain the following rows for `paa2013`:

`paa2013`: general result
`paa2013_pmid_1`: feature output for pmid 1
`paa2013_pmid_2`: feature output for pmid 2
`paa2013_pmid_n`: feature output for pmid n (where `n` is the number of articles for `paa2013` in the dataset).

ReCiter will construct a `uid` + underscore + `pmid` unique key and sends this key to DynamaDB to retrieve the analysis output for a **single** `uid` and `pmid` combination.

Advantages:

  * This will store a size of *only* a single article into the Analysis table which should be less than the 400 KB (the current limit set by DynamoDB).

Disadvatages:

  * The logic for retrieving the analysis output will be more complicated as it involves constructing a primary key from both the `uid` and `pmid`.

#### Store a pointer to S3 bucket in the DynamoDB table if the item size exceeds the size limitation.

Advantages:

  * The retrieval logic will not be modified to accomdate this change. However, the storage logic will need to check whether the size is greater than 400 KB and if it is, the storage logic will store the item in S3 and store the S3 location in DynamoDB entry.

Disadvantages:
  * Additional cost for S3.
  * Dataset stored in 2 different locations.

#### Store the compressed item in DynamoDB.

Advantages:

  * Not too much code change is required except for compressing the item when storing into DynamoDB and uncompressing the item when retrieving the item from DynamoDB.
  
Disadvantages:

  * Additional CPU cost for compressing and decompressing.

**Comment by sarbajitdutta** [comment]
This has been completed. Currently the items are checked if it gets a ValidationException( more than 400kb) then it stores the item in s3 in serialized json format. And also there is a flag in Analysis table which designates whether the data for ReCiterFeature is stored in s3 or not. 

Upon retrieval it checks whether the flag is set for isUsingS3 then it checks if s3 object exists with the keyname which is the uid if it exists it returns the object then uses Jacksons Object Mapper to map to a Object from a json. This has to be done since s3 uses InputStream and mostly stores file objects.
If the flag is not set then it retrieves as usual from the ReCiterFeature attribute in dynamodb.

Performance - While running ReCiter for a uid first time and the analysis exceeding 400kb it can take upto 10 seconds since it stores the item in dynamodb table and then the feature object in s3. But during retrieval of the same object it takes close to 1 to 2 seconds when invoking the analysisRefresh flag as false.
